name: basometro
dependencies:
- beautiful-soup=4.3.2=py34_0
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py34_0
- pip=7.0.3=py34_0
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.4=py34_0
- readline=6.2=2
- setuptools=17.1.1=py34_0
- six=1.9.0=py34_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - beautifulsoup4==4.3.2
